### ISSUE TITLE
missing arguments in "RestData" call

### ISSUE THREAD

**Issue by marttasch** [hwmland/homeassistant-xmrpool_stat#10]
## problem
There seems to be a problem with the current version of the Home Assistant Rest component. It will throw an error during component setup, that 2 positional arguments are missing. "encoding" and "ssl_cipher_list".

## solution
I fixed it by editing the RestData-call in "config_flow.py" (line 65) and "xmrpoolstat_controller.py" (line 39). I added the default values for this component.

For me the call works like this:
```
self._rest = RestData(
            self._hass,
            "GET",
            resource,
            auth=None,
            headers=None,
            params=None,
            data=None,
            verify_ssl=True,
            encoding='UTF-8',
            ssl_cipher_list='python_default',
        )
```

## enviroment
Home Assistant Core: 2023.6.1
Home Assistant OS: 10.2

**Comment by hwmland** [comment]
Thank you for investigating and fixing!

**Comment by marttasch** [comment]
You're welcome.
