### ISSUE TITLE
How to configure in HA

### ISSUE THREAD

**Issue by jotacor** [hwmland/homeassistant-xmrpool_stat#3]
Hi
I've been trying to configure this integration from HACS and I can't add the wallet, it doesn't show any input message to add it when I install it from HACS.
I tried also in configuration.yaml the following:

```
xmrpool_stat:
  wallet: wallet_hash
```
But I can't see the entity inside HA.

How I have to configure this integration inside HA??

**Comment by hwmland** [comment]
Hi,
you have to go into ```Configure Home Assistant``` - ```Integrations``` and press ```+ Add integration``` button
Than select ```XMR Pool Statistics``` from the list and following dialog should appear:
![image](https://user-images.githubusercontent.com/12407423/133129638-811062f7-2bf9-4a26-a24b-dd9aabd6c32d.png)

There you'll fill your wallet address and name (name is just for naming entities).
Configuration of wallet from yaml file is not supported. I hope it helps.
Just a note: if you find this integration useful, I'm going to publish another integration for collecting information from XMR Rig instances soon.

**Comment by DiabeticJedi** [comment]
Whenever I try to set it up using the configuration within HA I get the message "Invalid answer from server"

I did just start though so do I have to have the wallet for a while before it works?

**Comment by hwmland** [comment]
Hi, check on the page https://web.xmrpool.eu/ You can write your wallet there (abut middle of the screen), if it shows some statistics, it should be fine (I hope). 
Please check as well this thread: https://github.com/hwmland/homeassistant-xmrpool_stat/issues/4#issue-1059755344 to be sure it's not as well copy-pasting problem

**Comment by wchorski** [comment]
I see now my ignorance. This is the PI for XMRPool.eu. If i was mining a different pool, then this wouldn't work for my wallet. I wonder if i can fork this to work with my mining pool.
